baseURL = "https://appsbyrian.com/"
title = 'AppsByRian'
publishDir = "../appsbyrian/public"

[params]
  store = "https://cwq.appsbyrian.com"

# declare no taxonomies, otherwise hugo complains
[taxonomies]

# allow raw html in the content files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

